# This is a basic workflow to help you get started with Actions

name: TrackerJsCdnSync Build

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2

    # Install PHP composer
    - name: Install composer-installer
      uses: nanasess/composer-installer-action@v2.0.1

    # Install php dependencies
    - name: Install dependencies
      run: composer install --ignore-platform-reqs

    - name: PHP Syntax Checker (Lint)
      uses: StephaneBour/actions-php-lint@7.4

    - name: PHPUnit tests
      run: ./vendor/bin/phpunit --configuration tests/phpunit/phpunit.xml
